
import { ToolType } from "../types";

export interface AIPromptConfig {
  modelName: string;
  systemInstruction: string;
  generatePrompt: (inputs: Record<string, any>) => string;
}

export const getPromptConfig = (tool: ToolType, inputs: Record<string, any>): AIPromptConfig => {
  // Default fallback
  let config: AIPromptConfig = {
    modelName: 'gemini-2.5-flash',
    systemInstruction: 'You are a helpful AI assistant.',
    generatePrompt: () => inputs.content || "Hello, how can I help you today?"
  };

  const accentColor = inputs.accentColor || '#4f46e5';
  const template = inputs.template || 'modern';

  switch (tool) {
    // --- GERMAN MARKET SPECIALS ---
    case ToolType.INVOICE_GEN:
      // Helper to process line items
      const lineItems = Array.isArray(inputs.lineItems) ? inputs.lineItems : [];
      
      let subTotal = 0;
      let itemsListString = "";
      
      lineItems.forEach((item: any, index: number) => {
          const qty = parseFloat(item.quantity) || 0;
          const price = parseFloat(item.unitPrice) || 0;
          const total = qty * price;
          subTotal += total;
          itemsListString += `${index + 1}. ${item.description || 'Item'} | ${qty} x ${price.toFixed(2)} = ${total.toFixed(2)} €\n`;
      });

      // Calculate Totals based on Price Mode
      const vatRateStr = inputs.vatRate || "19%";
      const vatRate = parseFloat(vatRateStr.replace(/[^0-9.]/g, '')) / 100;
      const isGrossMode = inputs.priceMode === "Gross (Incl. VAT)";
      
      let netTotal = 0;
      let vatAmount = 0;
      let grossTotal = 0;

      if (isGrossMode) {
          grossTotal = subTotal;
          netTotal = grossTotal / (1 + vatRate);
          vatAmount = grossTotal - netTotal;
      } else {
          netTotal = subTotal;
          vatAmount = netTotal * vatRate;
          grossTotal = netTotal + vatAmount;
      }

      config = {
        modelName: 'gemini-2.5-flash',
        systemInstruction: `You are a German accounting expert and frontend developer.
        Your goal is to generate a legally compliant invoice (Rechnung) for the German market as a beautiful HTML document.
        
        Mandatory Fields (§14 UStG) to check/include:
        1. Full name & address of supplier (Leistender Unternehmer).
        2. Full name & address of recipient (Leistungsempfänger).
        3. Tax number (Steuernummer) or VAT ID (USt-IdNr).
        4. Date of issue (Ausstellungsdatum).
        5. Sequential invoice number (Rechnungsnummer).
        6. Description of goods/services (Menge und Art).
        7. Date of supply/service (Leistungszeitpunkt).
        8. Net amount, VAT rate, VAT amount, and Gross amount.
        
        Output Rules:
        - Return ONLY HTML code. No markdown code blocks (no \`\`\`html).
        - Use semantic HTML (h1, h2, h3, table, th, td, p). 
        - Do NOT use inline styles for colors or fonts. Rely on the parent container's CSS variables.
        - Structure:
          - Use <h1> for "RECHNUNG".
          - Use <table> for the item list with columns: Pos, Description, Qty, Unit Price, Total.
          - Align numbers to the right.
          - Add a 'total-row' class to the final sum row.`,
        generatePrompt: () => `
        Generate HTML Invoice.
        
        Type: ${inputs.invoiceType}
        Invoice Number: ${inputs.invoiceNumber || 'TBD'}
        Date: ${inputs.invoiceDate || 'Today'}
        Sender: ${inputs.senderDetails}
        Recipient: ${inputs.recipientDetails}
        
        LINE ITEMS (Pre-calculated):
        ${itemsListString}
        
        CALCULATED TOTALS:
        Net Total: ${netTotal.toFixed(2)} €
        VAT Rate: ${vatRateStr}
        VAT Amount: ${vatAmount.toFixed(2)} €
        Gross Total: ${grossTotal.toFixed(2)} €
        
        Payment Terms: ${inputs.paymentTerms}
        
        IMPORTANT: Return only the inner HTML structure (divs, tables) to be placed inside an A4 container. Use the provided calculated totals exactly.`
      };
      break;

    case ToolType.CONTRACT_GEN:
      const jurisdiction = inputs.jurisdiction || "General";
      
      config = {
        modelName: 'gemini-2.5-pro-preview', // Cost Optimization: 2.5 Pro for Reasoning
        systemInstruction: `You are a professional Legal Assistant AI specialized in drafting contracts.
        
        JURISDICTION CONTEXT: ${jurisdiction}. 
        You must apply the legal terminology and structure appropriate for this jurisdiction.
        - If Germany: Use "BGB" (Bürgerliches Gesetzbuch) standards.
        - If USA: Use standard Common Law or UCC structures.
        - If UK: Use English Law standards.
        
        SAFETY & DISCLAIMER (MANDATORY):
        The VERY FIRST ELEMENT of your HTML output MUST be a div with class "legal-disclaimer".
        Content: "<strong>DRAFT ONLY:</strong> This document is generated by AI and does not constitute legal advice. Review with a qualified attorney in your jurisdiction before signing."
        
        Structure & Style:
        - Return clean semantic HTML.
        - Do NOT use Markdown blocks.
        - Use <h1> for Title, <h2> for Sections (e.g. §1, Article 1).
        - Include a "Governing Law" clause matching the selected jurisdiction.
        - Include a "Severability" clause.
        
        Financials:
        - Clearly state price, currency, and payment terms in a dedicated section.
        `,
        generatePrompt: () => `
        Draft a ${inputs.contractType} for Jurisdiction: ${jurisdiction}.
        
        Date: ${inputs.contractDate || 'TBD'}
        Party A (Provider/Seller): ${inputs.partyA}
        Party B (Client/Buyer): ${inputs.partyB}
        
        Scope/Object: ${inputs.objectDetails}
        
        Financials:
        Price: ${inputs.price || '0'} ${inputs.currency || ''}
        Payment Method: ${inputs.paymentMethod}
        
        Conditions: ${inputs.conditions}
        
        Generate the complete HTML structure starting with the disclaimer.`
      };
      break;

    case ToolType.EMAIL_TEMPLATE:
      config = {
        modelName: 'gemini-2.0-flash-exp', // Cost Optimization: 2.0 Flash
        systemInstruction: `You are a Professional Business Communication Expert.
        Create a high-quality, effective email template based on the user's scenario.
        
        Output format: HTML.
        Style: Clean, readable, email-client friendly simulation.
        
        Structure:
        - Box for Subject Line options (use a div with class 'subject-box').
        - Main Email Body.
        - Placeholders: [Name], [Date] highlighted.`,
        generatePrompt: () => `Template Type: ${inputs.emailType}
        Recipient Info: ${inputs.recipientInfo}
        Key Points: ${inputs.keyPoints}
        Tone: ${inputs.tone}
        
        Generate the email template HTML.`
      };
      break;

    // --- UTILITY TOOLS ---
    case ToolType.TRANSLATE:
      config = {
        modelName: 'gemini-2.5-flash',
        systemInstruction: `You are a professional UN-level interpreter and translator. 
        Your task is to provide a translation that is not just literally correct, but culturally nuanced and native-sounding.
        Rules:
        1. Preserve the original tone (formal, casual, technical).
        2. Do NOT add preamble like "Here is the translation". Just output the target text.
        3. If the input is empty, return empty string.`,
        generatePrompt: () => `Source Text:\n"${inputs.content}"\n\nTarget Language: ${inputs.targetLang || 'English'}`
      };
      break;

    case ToolType.TEXT_POLISHER:
      config = {
        modelName: 'gemini-2.0-flash-exp', // Cost Optimization: 2.0 Flash
        systemInstruction: `You are an expert editor. Rewrite the text to match the requested goal/tone while fixing all grammar and clarity issues. Maintain the original meaning.`,
        generatePrompt: () => `Original Text:\n"${inputs.textToPolish}"\n\nGoal/Tone: ${inputs.polishGoal}`
      };
      break;

    case ToolType.SUMMARIZER:
      config = {
        modelName: 'gemini-2.5-flash',
        systemInstruction: `You are a precision summarizer. Condense the text according to the requested format.`,
        generatePrompt: () => `Text to Summarize:\n"${inputs.textToSummarize}"\n\nFormat: ${inputs.summaryFormat}`
      };
      break;

    case ToolType.DATA_ANALYSIS:
      config = {
        modelName: 'gemini-2.5-pro-preview', // Cost Optimization: 2.5 Pro for Reasoning
        systemInstruction: `You are a Senior Data Analyst. Analyze the provided data or text report.
        1. Identify key trends, anomalies, and insights.
        2. If raw data is provided, summarize it.
        3. Provide actionable recommendations based on the user's goal.`,
        generatePrompt: () => `Data/Report:\n"${inputs.data}"\n\nAnalysis Goal: ${inputs.goal}`
      };
      break;

    // --- CV & HR TOOLS ---
    case ToolType.CV_BUILDER:
      config = {
        modelName: 'gemini-2.5-pro-preview', // Cost Optimization: 2.5 Pro for Reasoning
        systemInstruction: `You are an expert Executive Career Coach and ATS-optimized Resume Writer with 20+ years of experience helping candidates land positions at Fortune 500 companies and top startups.

        CORE PRINCIPLES:
        1. Use the "CAR Method": Context (what was the situation) + Action (what you did) + Result (measurable impact)
        2. Start with powerful action verbs from different categories:
           - Leadership: Spearheaded, Orchestrated, Pioneered, Championed, Directed
           - Achievement: Achieved, Exceeded, Surpassed, Delivered, Accomplished
           - Improvement: Optimized, Streamlined, Transformed, Enhanced, Revolutionized
           - Technical: Developed, Engineered, Architected, Implemented, Automated
           - Collaboration: Collaborated, Coordinated, Facilitated, Partnered, Aligned

        3. ALWAYS quantify with specific metrics:
           - Numbers: "Led team of 12", "Managed $2M budget", "500+ users"
           - Percentages: "Reduced costs by 35%", "Improved performance 45%"
           - Time: "Delivered 2 weeks ahead of schedule", "In 6 months"
           - Scale: "Across 15 departments", "For 10,000+ customers"

        4. Include relevant keywords from the job description naturally
        5. Focus on business impact, not just tasks
        6. Use past tense for previous roles, present tense for current role
        7. Avoid buzzwords without context ("team player", "hard worker")

        OUTPUT FORMAT:
        - Return strictly HTML unordered list: <ul><li>...</li></ul>
        - Each bullet 1-2 lines maximum (15-25 words)
        - 4-6 bullets per role
        - No other text, explanation, or preamble

        EXAMPLES:
        Bad: "Responsible for improving website"
        Good: "Spearheaded website redesign that increased user engagement by 45% and reduced bounce rate from 58% to 32% within 3 months"

        Bad: "Managed social media accounts"
        Good: "Grew Instagram following from 5K to 50K in 6 months, achieving 3.2% average engagement rate and generating 200+ qualified leads"`,
        generatePrompt: () => {
          const jobTitle = inputs.jobTitle || 'the position';
          const company = inputs.company || 'the company';
          const description = inputs.content || inputs.description || '';
          const keywords = inputs.keywords || [];

          return `Generate 4-6 high-impact, ATS-optimized resume bullet points for this role:

Position: ${jobTitle}
Company: ${company}
${keywords.length > 0 ? `Key Skills to Include: ${keywords.join(', ')}` : ''}

Role Description/Achievements:
${description}

Remember:
- Use CAR method (Context + Action + Result)
- Start with powerful action verbs
- Include specific metrics and numbers
- Focus on business impact
- Make it ATS-friendly with relevant keywords
- Keep each bullet 15-25 words`;
        }
      };
      break;

    case ToolType.HR_JOB_DESC:
      config = {
        modelName: 'gemini-2.5-flash',
        systemInstruction: `You are a generic HR Specialist committed to writing inclusive, clear, and attractive job descriptions.`,
        generatePrompt: () => `Write a job description for a ${inputs.role} at ${inputs.company}.\n\nKey Responsibilities:\n${inputs.responsibilities}\n\nRequirements:\n${inputs.requirements}\n\nTone: ${inputs.tone}`
      };
      break;

    case ToolType.HR_INTERVIEW_PREP:
      config = {
        modelName: 'gemini-2.5-pro-preview', // Cost Optimization: 2.5 Pro for Reasoning
        systemInstruction: `You are a Hiring Manager. Generate a list of likely interview questions and suggested answers (STAR method) for the candidate.`,
        generatePrompt: () => `Role: ${inputs.role}\nIndustry: ${inputs.industry}\n\nProvide 5 behavioral and 5 technical questions with tips.`
      };
      break;

    // --- SOCIAL MEDIA ---
    case ToolType.SOCIAL_TWITTER:
      config = {
        modelName: 'gemini-2.0-flash-exp', // Cost Optimization: 2.0 Flash
        systemInstruction: `You are a viral Social Media Manager for Twitter/X.
        Your goal is to maximize engagement (likes, retweets).
        Rules:
        1. Be concise, punchy, and provocative.
        2. Use appropriate emojis but don't overdo it.
        3. Include 2-3 relevant hashtags at the end.
        4. If "Thread" is implied, separate tweets with "---".`,
        generatePrompt: () => `Write a ${inputs.tone} Twitter post/thread about: ${inputs.topic}.`
      };
      break;
    
    case ToolType.SOCIAL_LINKEDIN:
      config = {
        modelName: 'gemini-2.0-flash-exp', // Cost Optimization: 2.0 Flash
        systemInstruction: `You are a LinkedIn Top Voice and Thought Leader with 500K+ followers, known for creating viral, engaging professional content.

        PROVEN LINKEDIN STRUCTURE:
        1. HOOK (First 2 lines): Grab attention immediately
           - Use curiosity gaps, controversial takes, or bold claims
           - First line should stop the scroll
           - End with line break for "See more" placement

        2. STORY/CONTEXT: Personal anecdote or case study
           - Make it relatable and authentic
           - Use specific details (numbers, names, situations)
           - Show vulnerability or lessons learned

        3. VALUE/INSIGHT: The main teaching point
           - One clear, actionable takeaway
           - Back it up with data or examples
           - Make it memorable

        4. CALL-TO-ACTION: Encourage engagement
           - Ask a question
           - Request opinions
           - Invite sharing experiences

        ENGAGEMENT TACTICS:
        - Use short paragraphs (1-3 lines max)
        - Add strategic line breaks for readability
        - Use emojis sparingly (2-4 max) for visual breaks
        - Bold key phrases or numbers for emphasis
        - Write in first person (I/my) for authenticity
        - Include numbers and specific results
        - Tag relevant people/companies when appropriate

        TONE GUIDELINES:
        - Professional but conversational
        - Authentic, not salesy
        - Confident without arrogance
        - Helpful and generous
        - Storytelling over preaching

        OPTIMAL LENGTH: 150-300 words (LinkedIn sweet spot)`,
        generatePrompt: () => `Create a high-engagement LinkedIn post:

Topic: ${inputs.topic}
Target Audience: ${inputs.audience || 'professionals in the industry'}
Tone: ${inputs.tone || 'authentic and insightful'}
${inputs.goal ? `Goal: ${inputs.goal}` : ''}
${inputs.personalStory ? `Personal angle: ${inputs.personalStory}` : ''}

Requirements:
- Start with an attention-grabbing hook
- Include a personal story or specific example
- Provide one clear, actionable insight
- End with an engaging question
- Keep it authentic and conversational
- Use formatting for easy scanning
- Aim for 150-300 words`
      };
      break;

    // --- BLOG & EMAIL ---
    case ToolType.BLOG_INTRO:
      config = {
        modelName: 'gemini-2.5-flash',
        systemInstruction: `You are a professional blog writer. Write a captivating introduction that hooks the reader immediately.`,
        generatePrompt: () => `Topic: ${inputs.topic}\nTone: ${inputs.tone}\nHook Type: ${inputs.hookType}`
      };
      break;

    case ToolType.BLOG_FULL:
      config = {
        modelName: 'gemini-2.5-flash', // Optimized: Flash is excellent for long form text generation at low cost
        systemInstruction: `You are an expert SEO content strategist and professional blog writer with expertise in creating engaging, high-ranking content.

        CONTENT STRUCTURE:
        1. Compelling Hook: Start with a question, statistic, or story that grabs attention
        2. Clear Introduction: Set context, identify the problem, preview what's to come
        3. Well-organized Body: Use H2 and H3 headers for scanability
        4. Actionable Insights: Provide concrete examples, data, and takeaways
        5. Strong Conclusion: Summarize key points and include clear CTA

        SEO BEST PRACTICES:
        - Use primary keyword naturally in title, first paragraph, and 2-3 times in content
        - Include related keywords and semantic variations
        - Write descriptive, keyword-rich H2/H3 headers
        - Keep paragraphs short (2-4 sentences max) for readability
        - Use bullet points and numbered lists where appropriate
        - Include transition words for better flow

        ENGAGEMENT TECHNIQUES:
        - Write in second person (you/your) to connect with reader
        - Use active voice over passive voice
        - Include specific examples and case studies
        - Add data/statistics to build credibility
        - Use analogies and metaphors for complex concepts
        - Anticipate and answer reader objections

        OUTPUT FORMAT: Markdown with proper formatting
        - Use ## for H2, ### for H3
        - Use **bold** for emphasis
        - Use - for bullet lists, 1. for numbered lists
        - Include a "Key Takeaways" section with 3-5 bullets`,
        generatePrompt: () => `Write a comprehensive, SEO-optimized blog post:

Topic: ${inputs.topic}
Target Audience: ${inputs.audience || 'general readers'}
Tone: ${inputs.tone || 'professional yet conversational'}
Target Length: ${inputs.length || '1000-1500 words'}
${inputs.keywords ? `Primary Keywords: ${inputs.keywords}` : ''}
${inputs.outline ? `Follow this outline: ${inputs.outline}` : ''}

Requirements:
- Create an attention-grabbing headline
- Start with a compelling hook
- Use clear H2/H3 structure for easy scanning
- Include specific examples and data where relevant
- Make it actionable with concrete tips
- End with a strong conclusion and CTA
- Optimize for SEO while maintaining natural readability`
      };
      break;

    case ToolType.EMAIL_NEWSLETTER:
      config = {
        modelName: 'gemini-2.5-flash',
        systemInstruction: `You are an email marketing specialist. Write an engaging newsletter.`,
        generatePrompt: () => `Topic: ${inputs.topic}\nHighlights: ${inputs.highlights}\nCall to Action: ${inputs.cta}`
      };
      break;

    case ToolType.EMAIL_PROMO:
      config = {
        modelName: 'gemini-2.5-flash',
        systemInstruction: `You are an expert copywriter. Write a high-converting promotional email.`,
        generatePrompt: () => `Product: ${inputs.product}\nOffer: ${inputs.offer}\nUrgency: ${inputs.urgency}`
      };
      break;

    // --- SEO ---
    case ToolType.SEO_KEYWORDS:
      config = {
        modelName: 'gemini-2.5-flash',
        systemInstruction: `You are an SEO specialist. Generate a list of high-volume, relevant keywords.`,
        generatePrompt: () => `Topic: ${inputs.topic}\nRegion: ${inputs.region}`
      };
      break;

    case ToolType.SEO_META_TAGS:
      config = {
        modelName: 'gemini-2.5-flash',
        systemInstruction: `You are an SEO specialist. Write optimized Title Tags and Meta Descriptions.`,
        generatePrompt: () => `Topic: ${inputs.topic}\nKeyword: ${inputs.keyword}\nTone: ${inputs.tone}`
      };
      break;

    // --- STRATEGY ---
    case ToolType.STARTUP_VALIDATOR:
      config = {
        modelName: 'gemini-2.5-pro-preview', // Cost Optimization: 2.5 Pro for Reasoning
        systemInstruction: `You are a Startup Advisor. Analyze the idea using SWOT analysis and provide critical feedback.`,
        generatePrompt: () => `Startup Idea: ${inputs.idea}\nTarget Market: ${inputs.market}`
      };
      break;

    case ToolType.PRODUCT_DESC:
      config = {
        modelName: 'gemini-2.5-flash',
        systemInstruction: `You are a Product Marketer. Write compelling product descriptions that sell.`,
        generatePrompt: () => `Product Name: ${inputs.productName}\nFeatures: ${inputs.features}\nAudience: ${inputs.audience}`
      };
      break;
  }

  return config;
};
