
import { ToolType } from "../types";

export interface AIPromptConfig {
  modelName: string;
  systemInstruction: string;
  generatePrompt: (inputs: Record<string, any>) => string;
}

export const getPromptConfig = (tool: ToolType, inputs: Record<string, any>): AIPromptConfig => {
  // Default fallback
  let config: AIPromptConfig = {
    modelName: 'gemini-2.5-flash',
    systemInstruction: 'You are a helpful AI assistant.',
    generatePrompt: () => inputs.content || "Hello, how can I help you today?"
  };

  const accentColor = inputs.accentColor || '#4f46e5';
  const template = inputs.template || 'modern';

  switch (tool) {
    // --- GERMAN MARKET SPECIALS ---
    case ToolType.INVOICE_GEN:
      // Helper to process line items
      const lineItems = Array.isArray(inputs.lineItems) ? inputs.lineItems : [];
      
      let subTotal = 0;
      let itemsListString = "";
      
      lineItems.forEach((item: any, index: number) => {
          const qty = parseFloat(item.quantity) || 0;
          const price = parseFloat(item.unitPrice) || 0;
          const total = qty * price;
          subTotal += total;
          itemsListString += `${index + 1}. ${item.description || 'Item'} | ${qty} x ${price.toFixed(2)} = ${total.toFixed(2)} €\n`;
      });

      // Calculate Totals based on Price Mode
      const vatRateStr = inputs.vatRate || "19%";
      const vatRate = parseFloat(vatRateStr.replace(/[^0-9.]/g, '')) / 100;
      const isGrossMode = inputs.priceMode === "Gross (Incl. VAT)";
      
      let netTotal = 0;
      let vatAmount = 0;
      let grossTotal = 0;

      if (isGrossMode) {
          grossTotal = subTotal;
          netTotal = grossTotal / (1 + vatRate);
          vatAmount = grossTotal - netTotal;
      } else {
          netTotal = subTotal;
          vatAmount = netTotal * vatRate;
          grossTotal = netTotal + vatAmount;
      }

      config = {
        modelName: 'gemini-2.5-flash',
        systemInstruction: `You are a German accounting expert and frontend developer.
        Your goal is to generate a legally compliant invoice (Rechnung) for the German market as a beautiful HTML document.
        
        Mandatory Fields (§14 UStG) to check/include:
        1. Full name & address of supplier (Leistender Unternehmer).
        2. Full name & address of recipient (Leistungsempfänger).
        3. Tax number (Steuernummer) or VAT ID (USt-IdNr).
        4. Date of issue (Ausstellungsdatum).
        5. Sequential invoice number (Rechnungsnummer).
        6. Description of goods/services (Menge und Art).
        7. Date of supply/service (Leistungszeitpunkt).
        8. Net amount, VAT rate, VAT amount, and Gross amount.
        
        Output Rules:
        - Return ONLY HTML code. No markdown code blocks (no \`\`\`html).
        - Use semantic HTML (h1, h2, h3, table, th, td, p). 
        - Do NOT use inline styles for colors or fonts. Rely on the parent container's CSS variables.
        - Structure:
          - Use <h1> for "RECHNUNG".
          - Use <table> for the item list with columns: Pos, Description, Qty, Unit Price, Total.
          - Align numbers to the right.
          - Add a 'total-row' class to the final sum row.`,
        generatePrompt: () => `
        Generate HTML Invoice.
        
        Type: ${inputs.invoiceType}
        Invoice Number: ${inputs.invoiceNumber || 'TBD'}
        Date: ${inputs.invoiceDate || 'Today'}
        Sender: ${inputs.senderDetails}
        Recipient: ${inputs.recipientDetails}
        
        LINE ITEMS (Pre-calculated):
        ${itemsListString}
        
        CALCULATED TOTALS:
        Net Total: ${netTotal.toFixed(2)} €
        VAT Rate: ${vatRateStr}
        VAT Amount: ${vatAmount.toFixed(2)} €
        Gross Total: ${grossTotal.toFixed(2)} €
        
        Payment Terms: ${inputs.paymentTerms}
        
        IMPORTANT: Return only the inner HTML structure (divs, tables) to be placed inside an A4 container. Use the provided calculated totals exactly.`
      };
      break;

    case ToolType.CONTRACT_GEN:
      const jurisdiction = inputs.jurisdiction || "General";
      
      config = {
        modelName: 'gemini-2.5-pro-preview', // Cost Optimization: 2.5 Pro for Reasoning
        systemInstruction: `You are a professional Legal Assistant AI specialized in drafting contracts.
        
        JURISDICTION CONTEXT: ${jurisdiction}. 
        You must apply the legal terminology and structure appropriate for this jurisdiction.
        - If Germany: Use "BGB" (Bürgerliches Gesetzbuch) standards.
        - If USA: Use standard Common Law or UCC structures.
        - If UK: Use English Law standards.
        
        SAFETY & DISCLAIMER (MANDATORY):
        The VERY FIRST ELEMENT of your HTML output MUST be a div with class "legal-disclaimer".
        Content: "<strong>DRAFT ONLY:</strong> This document is generated by AI and does not constitute legal advice. Review with a qualified attorney in your jurisdiction before signing."
        
        Structure & Style:
        - Return clean semantic HTML.
        - Do NOT use Markdown blocks.
        - Use <h1> for Title, <h2> for Sections (e.g. §1, Article 1).
        - Include a "Governing Law" clause matching the selected jurisdiction.
        - Include a "Severability" clause.
        
        Financials:
        - Clearly state price, currency, and payment terms in a dedicated section.
        `,
        generatePrompt: () => `
        Draft a ${inputs.contractType} for Jurisdiction: ${jurisdiction}.
        
        Date: ${inputs.contractDate || 'TBD'}
        Party A (Provider/Seller): ${inputs.partyA}
        Party B (Client/Buyer): ${inputs.partyB}
        
        Scope/Object: ${inputs.objectDetails}
        
        Financials:
        Price: ${inputs.price || '0'} ${inputs.currency || ''}
        Payment Method: ${inputs.paymentMethod}
        
        Conditions: ${inputs.conditions}
        
        Generate the complete HTML structure starting with the disclaimer.`
      };
      break;

    case ToolType.EMAIL_TEMPLATE:
      config = {
        modelName: 'gemini-2.0-flash-exp', // Cost Optimization: 2.0 Flash
        systemInstruction: `You are a Professional Business Communication Expert.
        Create a high-quality, effective email template based on the user's scenario.
        
        Output format: HTML.
        Style: Clean, readable, email-client friendly simulation.
        
        Structure:
        - Box for Subject Line options (use a div with class 'subject-box').
        - Main Email Body.
        - Placeholders: [Name], [Date] highlighted.`,
        generatePrompt: () => `Template Type: ${inputs.emailType}
        Recipient Info: ${inputs.recipientInfo}
        Key Points: ${inputs.keyPoints}
        Tone: ${inputs.tone}
        
        Generate the email template HTML.`
      };
      break;

    // --- UTILITY TOOLS ---
    case ToolType.TRANSLATE:
      config = {
        modelName: 'gemini-2.5-flash',
        systemInstruction: `You are a professional UN-level interpreter and translator. 
        Your task is to provide a translation that is not just literally correct, but culturally nuanced and native-sounding.
        Rules:
        1. Preserve the original tone (formal, casual, technical).
        2. Do NOT add preamble like "Here is the translation". Just output the target text.
        3. If the input is empty, return empty string.`,
        generatePrompt: () => `Source Text:\n"${inputs.content}"\n\nTarget Language: ${inputs.targetLang || 'English'}`
      };
      break;

    case ToolType.TEXT_POLISHER:
      config = {
        modelName: 'gemini-2.0-flash-exp', // Cost Optimization: 2.0 Flash
        systemInstruction: `You are an expert editor. Rewrite the text to match the requested goal/tone while fixing all grammar and clarity issues. Maintain the original meaning.`,
        generatePrompt: () => `Original Text:\n"${inputs.textToPolish}"\n\nGoal/Tone: ${inputs.polishGoal}`
      };
      break;

    case ToolType.SUMMARIZER:
      config = {
        modelName: 'gemini-2.5-flash',
        systemInstruction: `You are a precision summarizer. Condense the text according to the requested format.`,
        generatePrompt: () => `Text to Summarize:\n"${inputs.textToSummarize}"\n\nFormat: ${inputs.summaryFormat}`
      };
      break;

    case ToolType.DATA_ANALYSIS:
      config = {
        modelName: 'gemini-2.5-pro-preview', // Cost Optimization: 2.5 Pro for Reasoning
        systemInstruction: `You are a Senior Data Analyst. Analyze the provided data or text report.
        1. Identify key trends, anomalies, and insights.
        2. If raw data is provided, summarize it.
        3. Provide actionable recommendations based on the user's goal.`,
        generatePrompt: () => `Data/Report:\n"${inputs.data}"\n\nAnalysis Goal: ${inputs.goal}`
      };
      break;

    // --- CV & HR TOOLS ---
    case ToolType.CV_BUILDER:
      config = {
        modelName: 'gemini-2.5-pro-preview', // Cost Optimization: 2.5 Pro for Reasoning
        systemInstruction: `You are an expert Executive Career Coach and Resume Writer with 20 years of experience.
        Your goal is to write high-impact, result-oriented bullet points using the "Action Verb + Task + Result" formula.
        Rules:
        1. Start every bullet with a strong power verb (e.g., Spearheaded, Orchestrated, Optimized).
        2. Quantify results with numbers/percentages whenever possible.
        3. Output strictly as an HTML Unordered List (<ul><li>...</li></ul>). No other text.`,
        generatePrompt: () => `Write 4-6 professional resume bullet points for the following role/description: "${inputs.content}".`
      };
      break;

    case ToolType.HR_JOB_DESC:
      config = {
        modelName: 'gemini-2.5-flash',
        systemInstruction: `You are a generic HR Specialist committed to writing inclusive, clear, and attractive job descriptions.`,
        generatePrompt: () => `Write a job description for a ${inputs.role} at ${inputs.company}.\n\nKey Responsibilities:\n${inputs.responsibilities}\n\nRequirements:\n${inputs.requirements}\n\nTone: ${inputs.tone}`
      };
      break;

    case ToolType.HR_INTERVIEW_PREP:
      config = {
        modelName: 'gemini-2.5-pro-preview', // Cost Optimization: 2.5 Pro for Reasoning
        systemInstruction: `You are a Hiring Manager. Generate a list of likely interview questions and suggested answers (STAR method) for the candidate.`,
        generatePrompt: () => `Role: ${inputs.role}\nIndustry: ${inputs.industry}\n\nProvide 5 behavioral and 5 technical questions with tips.`
      };
      break;

    // --- SOCIAL MEDIA ---
    case ToolType.SOCIAL_TWITTER:
      config = {
        modelName: 'gemini-2.0-flash-exp', // Cost Optimization: 2.0 Flash
        systemInstruction: `You are a viral Social Media Manager for Twitter/X.
        Your goal is to maximize engagement (likes, retweets).
        Rules:
        1. Be concise, punchy, and provocative.
        2. Use appropriate emojis but don't overdo it.
        3. Include 2-3 relevant hashtags at the end.
        4. If "Thread" is implied, separate tweets with "---".`,
        generatePrompt: () => `Write a ${inputs.tone} Twitter post/thread about: ${inputs.topic}.`
      };
      break;
    
    case ToolType.SOCIAL_LINKEDIN:
      config = {
        modelName: 'gemini-2.0-flash-exp', // Cost Optimization: 2.0 Flash
        systemInstruction: `You are a LinkedIn Top Voice and Thought Leader.
        Goal: Build professional authority and network engagement.
        Structure: Hook, Meat, Takeaway, Ask.
        Format: Short paragraphs, bold key phrases.`,
        generatePrompt: () => `Topic: ${inputs.topic}\nTarget Audience: ${inputs.audience}\nTone: ${inputs.tone}`
      };
      break;

    // --- BLOG & EMAIL ---
    case ToolType.BLOG_INTRO:
      config = {
        modelName: 'gemini-2.5-flash',
        systemInstruction: `You are a professional blog writer. Write a captivating introduction that hooks the reader immediately.`,
        generatePrompt: () => `Topic: ${inputs.topic}\nTone: ${inputs.tone}\nHook Type: ${inputs.hookType}`
      };
      break;

    case ToolType.BLOG_FULL:
      config = {
        modelName: 'gemini-2.5-flash', // Optimized: Flash is excellent for long form text generation at low cost
        systemInstruction: `You are an expert content writer. Write a comprehensive, SEO-optimized blog post. 
        Use H2 and H3 headers. Output in Markdown.`,
        generatePrompt: () => `Topic: ${inputs.topic}\nAudience: ${inputs.audience}\nTone: ${inputs.tone}\nLength: ${inputs.length}`
      };
      break;

    case ToolType.EMAIL_NEWSLETTER:
      config = {
        modelName: 'gemini-2.5-flash',
        systemInstruction: `You are an email marketing specialist. Write an engaging newsletter.`,
        generatePrompt: () => `Topic: ${inputs.topic}\nHighlights: ${inputs.highlights}\nCall to Action: ${inputs.cta}`
      };
      break;

    case ToolType.EMAIL_PROMO:
      config = {
        modelName: 'gemini-2.5-flash',
        systemInstruction: `You are an expert copywriter. Write a high-converting promotional email.`,
        generatePrompt: () => `Product: ${inputs.product}\nOffer: ${inputs.offer}\nUrgency: ${inputs.urgency}`
      };
      break;

    // --- SEO ---
    case ToolType.SEO_KEYWORDS:
      config = {
        modelName: 'gemini-2.5-flash',
        systemInstruction: `You are an SEO specialist. Generate a list of high-volume, relevant keywords.`,
        generatePrompt: () => `Topic: ${inputs.topic}\nRegion: ${inputs.region}`
      };
      break;

    case ToolType.SEO_META_TAGS:
      config = {
        modelName: 'gemini-2.5-flash',
        systemInstruction: `You are an SEO specialist. Write optimized Title Tags and Meta Descriptions.`,
        generatePrompt: () => `Topic: ${inputs.topic}\nKeyword: ${inputs.keyword}\nTone: ${inputs.tone}`
      };
      break;

    // --- STRATEGY ---
    case ToolType.STARTUP_VALIDATOR:
      config = {
        modelName: 'gemini-2.5-pro-preview', // Cost Optimization: 2.5 Pro for Reasoning
        systemInstruction: `You are a Startup Advisor. Analyze the idea using SWOT analysis and provide critical feedback.`,
        generatePrompt: () => `Startup Idea: ${inputs.idea}\nTarget Market: ${inputs.market}`
      };
      break;

    case ToolType.PRODUCT_DESC:
      config = {
        modelName: 'gemini-2.5-flash',
        systemInstruction: `You are a Product Marketer. Write compelling product descriptions that sell.`,
        generatePrompt: () => `Product Name: ${inputs.productName}\nFeatures: ${inputs.features}\nAudience: ${inputs.audience}`
      };
      break;
  }

  return config;
};
